### PR TITLE
Readds the Autodoc

### PR DESCRIPTION
**Pull request by Orchidthederg**
## About The Pull Request

Readds the Autodoc to the codebase as KubeRoot requested.

## Why It's Good For The Game

WHAT DO WE WANT? Implants on deadpop! WHEN DO WE WANT IT?! NOW!!

## Changelog
:cl:
add: Added the Autodoc
/:cl:

### CODE REVIEW

**Comment by Orchidthederg** [comment]
Tested, works as intended.

**Review by Laboredih123 — APPROVED** [review]
Looks fine to me

**Comment by Laboredih123** [comment]
Tested and works. I think we can merge

**Review by MaltVinegar — APPROVED** [review]
👍

**Review by KubeRoot — APPROVED** [review]

**Pull request merged**
